### ISSUE TITLE
Projects => Project Detail => Files should be readonly (no Add btn)

### ISSUE THREAD

**Issue by tungpham** [tungpham/bcfe#57]

**Comment by Darko-Vasilev** [comment]
fixed. please check.

**Comment by tungpham** [comment]
I'm logged in as test4@bc.com, project "test" is created by nhulongctk10@gmail.com. When I click on "test" from Projects, Files, I still see the Add button.
